### ISSUE TITLE
it should be possible to have pyff stop a pipline unless all load statements succeed

### ISSUE THREAD

**Issue by leifj** [leifj/pyFF#62]
This is related to #61

**Comment by leifj** [comment]
Thinking about how to implement this in the load pipeline it looks like it will be quite involved because of the complex error handling in that function. My thought is instead to do a separate "check" pipeline that can be used as a kind of assert-like function that checks that a set of conditions hold in the current active store and fails appropriately otherwize. For instance it could look something like this:

```yaml
- load:
   - source1 as ONE
   - source2 as TWO
- check:
   - entityID_1 in ONE # true iff entityID_1 is in collection ONE
   - any in entities   # entities == the full collection
   - entityID_2 in entities # true iff entityID_1 is any collection
```
