### ISSUE TITLE
Some entities with specific descriptor not filtered

### ISSUE THREAD

**Issue by andrius-kulbis** [leifj/pyFF#91]
I have the following configuration for eduGAIN metadata signing:

```
- load:
   - http://mds.edugain.org/feed-sha256.xml as edugain-md certs/eduGAIN-signer-ca.pem
- select:
- fork:
   - select:
      - "edugain-md!md:EntityDescriptor[md:IDPSSODescriptor]"
   - xslt:
      stylesheet: tidy.xsl
   - finalize:
      cacheDuration: PT5H
      validUntil: P5D
   - sign:
      key: certs/key.pem
      cert: certs/cert.crt
   - publish:
      - /var/www/output-edugain/metadata.edugain+idp.xml
 
- fork:
   - select:
      - "edugain-md!md:EntityDescriptor[md:SPSSODescriptor]"
   - xslt:
      stylesheet: tidy.xsl
   - finalize:
      cacheDuration: PT5H
      validUntil: P5D
   - sign:
      key: certs/key.pem
      cert: certs/cert.crt
   - publish:
      - /var/www/output-edugain/metadata.edugain+sp.xml
 
- xslt:
   stylesheet: tidy.xsl
- finalize:
   cacheDuration: PT5H
   validUntil: P5D
- sign:
   key: certs/key.pem
   cert: certs/cert.crt
- publish:
   - /var/www/output-edugain/metadata.edugain.xml
```

After running the tool, I get mixed results: some entities with md:SPSSODescriptor in metadata.edugain+idp.xml and md:IDPSSODescriptor in  metadata.edugain+sp.xml left unfiltered. Is there anything wrong with my configuration?

 I am using 0.10.0.dev0 version on Debian Jessie.

**EDIT:**

Figured out this happens with EntityDescriptor element, which has md:SPSSODescriptor and md:IDPSSODescriptor tag inside at the same time. Is it possible to remove the unwanted element without removing all the  EntityDescriptor?

**Comment by andrius-kulbis** [comment]
Found the solution with the `prune` option:
```
...
- fork:
   - select:
      - "edugain-md!md:EntityDescriptor[md:IDPSSODescriptor]"
   - prune:
      - .//{urn:oasis:names:tc:SAML:2.0:metadata}SPSSODescriptor
...
```
